/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SolutionsIndexRouteImport } from './routes/solutions.index'
import { Route as IndustriesIndexRouteImport } from './routes/industries.index'
import { Route as SolutionsSolutionIdRouteImport } from './routes/solutions.$solutionId'
import { Route as PresentSolutionIdRouteImport } from './routes/present.$solutionId'
import { Route as PresentIndustryIndustryIdRouteImport } from './routes/present-industry.$industryId'
import { Route as IndustriesIndustryIdRouteImport } from './routes/industries.$industryId'

const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsIndexRoute = SolutionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SolutionsRoute,
} as any)
const IndustriesIndexRoute = IndustriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IndustriesRoute,
} as any)
const SolutionsSolutionIdRoute = SolutionsSolutionIdRouteImport.update({
  id: '/$solutionId',
  path: '/$solutionId',
  getParentRoute: () => SolutionsRoute,
} as any)
const PresentSolutionIdRoute = PresentSolutionIdRouteImport.update({
  id: '/present/$solutionId',
  path: '/present/$solutionId',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentIndustryIndustryIdRoute =
  PresentIndustryIndustryIdRouteImport.update({
    id: '/present-industry/$industryId',
    path: '/present-industry/$industryId',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndustriesIndustryIdRoute = IndustriesIndustryIdRouteImport.update({
  id: '/$industryId',
  path: '/$industryId',
  getParentRoute: () => IndustriesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/industries': typeof IndustriesRouteWithChildren
  '/solutions': typeof SolutionsRouteWithChildren
  '/industries/$industryId': typeof IndustriesIndustryIdRoute
  '/present-industry/$industryId': typeof PresentIndustryIndustryIdRoute
  '/present/$solutionId': typeof PresentSolutionIdRoute
  '/solutions/$solutionId': typeof SolutionsSolutionIdRoute
  '/industries/': typeof IndustriesIndexRoute
  '/solutions/': typeof SolutionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/industries/$industryId': typeof IndustriesIndustryIdRoute
  '/present-industry/$industryId': typeof PresentIndustryIndustryIdRoute
  '/present/$solutionId': typeof PresentSolutionIdRoute
  '/solutions/$solutionId': typeof SolutionsSolutionIdRoute
  '/industries': typeof IndustriesIndexRoute
  '/solutions': typeof SolutionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/industries': typeof IndustriesRouteWithChildren
  '/solutions': typeof SolutionsRouteWithChildren
  '/industries/$industryId': typeof IndustriesIndustryIdRoute
  '/present-industry/$industryId': typeof PresentIndustryIndustryIdRoute
  '/present/$solutionId': typeof PresentSolutionIdRoute
  '/solutions/$solutionId': typeof SolutionsSolutionIdRoute
  '/industries/': typeof IndustriesIndexRoute
  '/solutions/': typeof SolutionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/industries'
    | '/solutions'
    | '/industries/$industryId'
    | '/present-industry/$industryId'
    | '/present/$solutionId'
    | '/solutions/$solutionId'
    | '/industries/'
    | '/solutions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/industries/$industryId'
    | '/present-industry/$industryId'
    | '/present/$solutionId'
    | '/solutions/$solutionId'
    | '/industries'
    | '/solutions'
  id:
    | '__root__'
    | '/'
    | '/industries'
    | '/solutions'
    | '/industries/$industryId'
    | '/present-industry/$industryId'
    | '/present/$solutionId'
    | '/solutions/$solutionId'
    | '/industries/'
    | '/solutions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IndustriesRoute: typeof IndustriesRouteWithChildren
  SolutionsRoute: typeof SolutionsRouteWithChildren
  PresentIndustryIndustryIdRoute: typeof PresentIndustryIndustryIdRoute
  PresentSolutionIdRoute: typeof PresentSolutionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/': {
      id: '/solutions/'
      path: '/'
      fullPath: '/solutions/'
      preLoaderRoute: typeof SolutionsIndexRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/industries/': {
      id: '/industries/'
      path: '/'
      fullPath: '/industries/'
      preLoaderRoute: typeof IndustriesIndexRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/solutions/$solutionId': {
      id: '/solutions/$solutionId'
      path: '/$solutionId'
      fullPath: '/solutions/$solutionId'
      preLoaderRoute: typeof SolutionsSolutionIdRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/present/$solutionId': {
      id: '/present/$solutionId'
      path: '/present/$solutionId'
      fullPath: '/present/$solutionId'
      preLoaderRoute: typeof PresentSolutionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/present-industry/$industryId': {
      id: '/present-industry/$industryId'
      path: '/present-industry/$industryId'
      fullPath: '/present-industry/$industryId'
      preLoaderRoute: typeof PresentIndustryIndustryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/$industryId': {
      id: '/industries/$industryId'
      path: '/$industryId'
      fullPath: '/industries/$industryId'
      preLoaderRoute: typeof IndustriesIndustryIdRouteImport
      parentRoute: typeof IndustriesRoute
    }
  }
}

interface IndustriesRouteChildren {
  IndustriesIndustryIdRoute: typeof IndustriesIndustryIdRoute
  IndustriesIndexRoute: typeof IndustriesIndexRoute
}

const IndustriesRouteChildren: IndustriesRouteChildren = {
  IndustriesIndustryIdRoute: IndustriesIndustryIdRoute,
  IndustriesIndexRoute: IndustriesIndexRoute,
}

const IndustriesRouteWithChildren = IndustriesRoute._addFileChildren(
  IndustriesRouteChildren,
)

interface SolutionsRouteChildren {
  SolutionsSolutionIdRoute: typeof SolutionsSolutionIdRoute
  SolutionsIndexRoute: typeof SolutionsIndexRoute
}

const SolutionsRouteChildren: SolutionsRouteChildren = {
  SolutionsSolutionIdRoute: SolutionsSolutionIdRoute,
  SolutionsIndexRoute: SolutionsIndexRoute,
}

const SolutionsRouteWithChildren = SolutionsRoute._addFileChildren(
  SolutionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IndustriesRoute: IndustriesRouteWithChildren,
  SolutionsRoute: SolutionsRouteWithChildren,
  PresentIndustryIndustryIdRoute: PresentIndustryIndustryIdRoute,
  PresentSolutionIdRoute: PresentSolutionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
